[build]
  base = "client-app"
  publish = "client-app/dist"
  command = "npm install --legacy-peer-deps && npm run dev"

[context.production.environment]
  NODE_VERSION = "22.17.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
