[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[context.production.environment]
  NODE_VERSION = "22.17.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
